// Central product data file — add/update/remove products here

export type Product = {
    id: string;
    model: string;
    name: string;
    category: 'Tea Picking' | 'Hedge Trimmer' | 'Pole Multi-Tool' | 'Lawn Mower' | 'Scarifier' | 'Blower';
    powerType: 'Lithium Battery' | 'Gasoline';
    badge: string;
    shortDesc: string;
    longDesc: string;
    specs: { label: string; value: string }[];
    features: string[];
    image: string; // URL or /public path
    inStock: boolean;
    isNew?: boolean;
    isBestseller?: boolean;
};

export const products: Product[] = [
    // ── TEA PICKING MACHINES ──────────────────────────────────────────────
    {
        id: 'oll-340',
        model: 'OLL-340',
        name: 'Lithium Battery Tea Picking Machine',
        category: 'Tea Picking',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: 'Professional tea picker with stepless voltage speed control. Lightweight at 1.45kg with 24V brushless motor for all-day operation.',
        longDesc: 'The OLL-340 Tea Picking Machine features a comfortable ergonomic handle design that is more in line with human mechanics, making it lighter to use. Large capacity lithium battery with high-quality batteries for more durable battery life. Efficient heat dissipation ensures long-lasting, stable continuous operation without burning the machine.',
        specs: [
            { label: 'Motor', value: 'Brushless / Stepless voltage speed change' },
            { label: 'Battery', value: '24V — 2.5 / 8 / 10 / 12 / 20 AH' },
            { label: 'Charging Time', value: '3.5–20h' },
            { label: 'Net Weight', value: '1.45 kg' },
            { label: 'Product Size', value: '55×15×15 cm' },
            { label: 'Container Qty', value: '20ft: 672 pc | 40ft HQ: 2,428 pc' },
        ],
        features: [
            'Stepless voltage speed control',
            'Long-lasting lithium battery (up to 20AH)',
            'Efficient heat dissipation',
            'Ergonomic handle design',
            'Suitable for tea gardens & orchards',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=dQrEW8LLBM8luaybD%2BhX7aPtFvB8F%2FMmD%2FbBmco8UARxVQvxG8nIMaB0cIbq3HZUJxQpNkqfi7MywEYSt42Zl%2Bbj6xDnYzC%2F%2Fus0lEg2HeUVpyLPcPQGWXFCDsGfpgCld0CPaFRCt7GD2vhdkVUc%2Fkb6wo4EudGxTKw0F0WLld6IAx1NzuKah5oRVuYxOdYT1dwMQm7exYOfE%2FCws5Wd2QQtbwK4g5MBTumSJb4I3jLKeqM1wKyFMpdxLiB8vRWe8fr%2BsGSTPo0%3D&u2=KVsHtfZSEbm568Io&width=2560',
        inStock: true,
        isBestseller: true,
    },
    {
        id: 'oll-340a',
        model: 'OLL-340A',
        name: 'Tea Picking Machine (Curved Blade)',
        category: 'Tea Picking',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: 'Curved blade variant of the OLL-340 for optimum reach in dense tea bushes. 24V brushless motor, 1.2kg.',
        longDesc: 'The OLL-340A features a curved straight blade design for optimum performance in dense tea plantations. Shares the same powerful brushless motor and lithium battery system as the OLL-340 but with a replaceable blade system for added versatility.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor' },
            { label: 'Battery', value: '24V — 2.5 / 8 / 10 / 12 / 20 AH' },
            { label: 'Charging Time', value: '2.5 - 9h / 2.5 - 8h' },
            { label: 'Net Weight', value: '1.2 kg' },
            { label: 'Product Size', value: '65×9×14 cm' },
            { label: 'Container Qty', value: '20ft: 756 pc | 40ft HQ: 2,104 pc' },
        ],
        features: [
            'Replaceable curved blade',
            '24V lithium battery system',
            'Brushless motor',
            'Suitable for deep bush picking',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=dbpFBs3E6zhXuVKZx3dEl0aJU1koHzsEvl2S8SrP4iSkz3d9b2PgxmTx5C8szG7N%2F1lZmj93WUFlgyxacqFaxbjyaNmtV5iqMFc86AsV%2FqmFLe1teULp47zZTNQVR0%2FC2LSDldWb%2FL756673I3Zp5xQ5&u2=5JpT1RqvDA0tgQNr&width=2560',
        inStock: true,
    },
    {
        id: 'oll-260',
        model: 'OLL-260',
        name: 'Mini Tea Picking Machine',
        category: 'Tea Picking',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: 'Compact, lightweight hand-held tea picker for small plots and steep terrain. Perfect for one-person operation.',
        longDesc: 'The OLL-260 is our smallest and most maneuverable tea picking machine. Ideal for small tea gardens, steep hillside plantations, or areas too narrow for larger machines. Despite its compact size, it delivers professional-grade performance with a reliable lithium battery.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor' },
            { label: 'Battery', value: '24V Lithium' },
            { label: 'Net Weight', value: '1.0 kg' },
            { label: 'Design', value: 'Single-hand operation' },
        ],
        features: [
            'Ultra-lightweight design',
            'Single-hand operation',
            'Great for narrow/steep terrain',
            'Long battery life',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=rBD5hX%2FNJwMKAZePr5VbrOycBnlAJrjZFS%2B5pHYlCN0LaSQ4HmvprG99PnhIB6T%2FpsoWVkR9RXC%2BxPUVne58Zi2MyCn3qQ5266Gd6hpZoApycqp8WPx%2BtZRaJjs8TvzL156d%2FHP9hL9444vYrDNIF4bWJqgdza9A&u2=Ws94fiX6pb%2F15OBA&width=2560',
        inStock: true,
        isNew: true,
    },

    // ── HEDGE TRIMMERS ───────────────────────────────────────────────────
    {
        id: 'oll-340-ht',
        model: 'OLL-340 HT',
        name: 'Straight Blade Hedge Trimmer',
        category: 'Hedge Trimmer',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: '450mm straight blade professional hedge trimmer. 5900 RPM, 24V brushless, 1.2kg. Perfect for clean garden edges.',
        longDesc: 'Professional-grade straight blade hedge trimmer with 450mm blade length. The brushless motor delivers 5900 RPM for clean, precise cuts through thick hedges. Lightweight design at 1.2kg reduces fatigue during extended operations.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor' },
            { label: 'Speed', value: '5900 RPM' },
            { label: 'Voltage', value: '24V' },
            { label: 'Load Current', value: '1.2A' },
            { label: 'Net Weight', value: '1.2 kg' },
            { label: 'Blade Length', value: '450mm' },
            { label: 'Product Size', value: '65×9×14 cm' },
            { label: 'Battery Options', value: '24V 8Ah / 12Ah / 20Ah' },
        ],
        features: [
            '450mm straight blade',
            'Brushless high-speed motor',
            'Ergonomic anti-vibration handle',
            'Compatible with multiple battery capacities',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=F7D08NLe%2BnInqlYz5LIV03%2BaZ%2BBC3HC7CWvE%2BWL0PmdLO42BVukmwgbXmDyzh221u0OgCbAkfSxLWknArMfQEwgCh4QIQwWWlBGTCRQ8kq9eh4WUrZtwlw%3D%3D&u2=CTT2rxq4uAwNC85G&width=2560',
        inStock: true,
        isBestseller: true,
    },
    {
        id: 'oll-500m',
        model: 'OLL-500M',
        name: 'Straight Blade Hedge Trimmer Pro',
        category: 'Hedge Trimmer',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: '500mm blade, 5900 RPM professional hedge trimmer. Lighter 1.2 kg frame for comfortable extended use.',
        longDesc: 'The OLL-500M is a professional-grade trimmer with a longer 500mm blade, ideal for larger hedges and shrubs. Same powerful brushless motor as the OLL-340 HT but with an extended blade for wider cutting coverage per pass.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor' },
            { label: 'Speed', value: '5900 RPM' },
            { label: 'Voltage', value: '24V' },
            { label: 'Net Weight', value: '1.2 kg' },
            { label: 'Blade Length', value: '500mm' },
            { label: 'Product Size', value: '63×9×14 cm' },
            { label: 'Battery Options', value: '24V 8Ah / 12Ah / 20Ah' },
        ],
        features: [
            '500mm wider blade coverage',
            'High-speed 5900 RPM brushless',
            'Lightweight ergonomic frame',
            'Low vibration for fatigue-free use',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=EsYbANrTCpwc2oE3fBmHO8ObYFFivuAmFbsziCEfnTBXgHWShpd3sy7re6shlX4hJNI%2F4NjSdQmyctc7zMk1y5jUuXRi8SCL9s6aJQQQFmFjyuqW5EVb0WlvwNwpQUIgCRlD6146u9XVyDViK%2FxYw%2BNpRA3tqsghu%2FQB07im573gslFNxa8MGd6%2BAz6x&u2=WEC1IhSiFDg%2FIQXI&width=2560',
        inStock: true,
    },
    {
        id: 'oll-360b',
        model: 'OLL-360B',
        name: 'Curved Blade Hedge Trimmer',
        category: 'Hedge Trimmer',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: 'Curved blade design for reaching awkward angles and under-cuts. 24V brushless, 1.2kg.',
        longDesc: 'The OLL-360B features a specially curved blade for cutting at angles and reaching areas that straight-blade trimmers cannot. Ideal for topiary, shaped hedges, and under-cutting dense shrubs.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor' },
            { label: 'Charging Time', value: '2.5–9h / 2.5–8h' },
            { label: 'Net Weight', value: '1.2 kg' },
            { label: 'Product Size', value: '65×9×14 cm' },
            { label: 'Battery Options', value: '24V 8Ah / 12Ah / 20Ah / 23Ah' },
        ],
        features: [
            'Curved blade for angular cuts',
            'Ideal for topiary and shaped hedges',
            'Brushless long-life motor',
            'Multiple battery options',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=mdWGRuRu7M9coEOeb4R6j9ABXVktebjsEF%2BYA7dzlWYyIQTH3fnvE3IIcBNZ%2BfxWJGlXz4wiz1BLiwMIzmTRjMosDLAleBPoHHRDCcJDFM2IjluHl%2B8UHRWKsfCcwotTxIZN6OAislEodpqsk5kzM%2F%2FAvN8r5fs0%2B41RVwol8PnzM9TMNOIK%2BpFRrN6SWTuIAO61swmIPFDgsRDOQp2zLte2fyeVOLMD63igTg5VbGGgRBG%2FV%2B%2FigODg8VXJMdf0fp%2FLyaXOsNYgLUFnOx%2FH&u2=5m0OZTQN6PIhyiAl&width=2560',
        inStock: true,
    },
    {
        id: 'oll-450b',
        model: 'OLL-450B',
        name: 'Straight Blade Hedge Trimmer 450B',
        category: 'Hedge Trimmer',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: 'Heavy-duty 450mm straight blade trimmer for commercial use. High torque brushless motor with long run time.',
        longDesc: 'The OLL-450B is designed for commercial landscaping and large-scale garden management. The heavy-duty frame and high-torque brushless motor can handle thick woody stems with ease.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor' },
            { label: 'Charging Time', value: '2.5–9h / 2.5–8h' },
            { label: 'Net Weight', value: '1.2 kg' },
            { label: 'Product Size', value: '63×9×14 cm' },
            { label: 'Battery Options', value: '24V 8Ah / 12Ah / 20Ah / 23Ah' },
        ],
        features: [
            'Commercial-grade heavy duty',
            '450mm high-torque blade',
            'Cuts thick woody stems',
            'Extended battery run time',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=1sQxCdyr3Duhy%2BjlShcY3IohltN0UaSE9uMlupGQm65dIb5k2BBIVaHQBptYIhwAGJFut5beI%2B%2FYjF5fawLlY%2BxpGA52R6488B9nXvauHmjy7WNwpg%3D%3D&u2=gQNxcW7bFvGj5jHw&width=2560',
        inStock: true,
        isNew: true,
    },
    {
        id: 'oll-600b',
        model: 'OLL-600B',
        name: 'Double Blade Hedge Trimmer',
        category: 'Hedge Trimmer',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: 'Multifunctional double-blade hedge trimmer. Long-lasting battery life with professional-grade dual cutting edges.',
        longDesc: 'The OLL-600B is our flagship multifunctional double-blade hedge trimmer. With dual cutting edges, you can cut on both left and right strokes for twice the efficiency. Long-lasting battery life ensures you can work through large gardens without stopping.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor' },
            { label: 'Blade Type', value: 'Double Blade' },
            { label: 'Voltage', value: '24V' },
            { label: 'Feature', value: 'Multifunctional' },
        ],
        features: [
            'Double-blade dual-edge cutting',
            '2x efficiency — cuts on both strokes',
            'Multifunctional tool head',
            'Long-lasting battery life',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=I6AHtSfsTiMgKXkcNz2D0MdkbAxu61iSF%2BjDaPYPixcNm9pfAm3hmaxv%2FkO19rvCU3wo%2F1u%2BqNFOaosrNNE%2BCFeiiKNeEWVGvzgrmA%3D%3D&u2=Q%2FkD%2F3XvXsnN%2BsH5&width=2560',
        inStock: true,
        isBestseller: true,
        isNew: true,
    },

    // ── POLE MULTI-TOOLS ─────────────────────────────────────────────────
    {
        id: 'oll-st5002',
        model: 'OLL-ST5002',
        name: 'Scalable Pole Multi-Tool (Chainsaw Head)',
        category: 'Pole Multi-Tool',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: 'Telescopic pole tool (0.75–3.2m) with chainsaw attachment. Reach high branches safely from the ground.',
        longDesc: 'The OLL-ST5002 Scalable Pole Multi-Tool extends from 0.75m to 3.2m and accepts interchangeable heads including a chainsaw and hedge trimmer. High-power brushless motor ensures cutting performance even at full extension.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor (High Power)' },
            { label: 'Pole Length', value: '0.75m – 3.2m (scalable)' },
            { label: 'Head', value: 'Chainsaw (interchangeable)' },
            { label: 'Voltage', value: '24V' },
        ],
        features: [
            'Telescopic 0.75m–3.2m pole',
            'Interchangeable chainsaw head',
            'Ground-level high-branch cutting',
            'High-power brushless motor',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=dbpFBs3E6zhXuVKZx3dEl0aJU1koHzsEvl2S8SrP4iSkz3d9b2PgxmTx5C8szG7N%2F1lZmj93WUFlgyxacqFaxbjyaNmtV5iqMFc86AsV%2FqmFLe1teULp47zZTNQVR0%2FC2LSDldWb%2FL756673I3Zp5xQ5&u2=5JpT1RqvDA0tgQNr&width=2560',
        inStock: true,
        isNew: true,
    },
    {
        id: 'oll-st5003',
        model: 'OLL-ST5003',
        name: 'Scalable Pole Multi-Tool (Trimmer Head)',
        category: 'Pole Multi-Tool',
        powerType: 'Lithium Battery',
        badge: 'Lithium Powered',
        shortDesc: 'Telescopic pole tool with hedge trimmer attachment. Trim high hedges and topiary up to 3.2m safely.',
        longDesc: 'The OLL-ST5003 variant of the scalable pole series comes with a hedge trimmer head instead of a chainsaw. Perfect for maintaining tall hedges, topiary, and tree rows from the safety of the ground.',
        specs: [
            { label: 'Motor', value: 'Brushless Motor (High Power)' },
            { label: 'Pole Length', value: '0.75m – 3.2m (scalable)' },
            { label: 'Head', value: 'Hedge Trimmer (interchangeable)' },
            { label: 'Voltage', value: '24V' },
        ],
        features: [
            'Telescopic 0.75m–3.2m pole',
            'Hedge trimmer head',
            'Trim tall hedges from ground level',
            'Same platform as ST5002',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=rBD5hX%2FNJwMKAZePr5VbrOycBnlAJrjZFS%2B5pHYlCN0LaSQ4HmvprG99PnhIB6T%2FpsoWVkR9RXC%2BxPUVne58Zi2MyCn3qQ5266Gd6hpZoApycqp8WPx%2BtZRaJjs8TvzL156d%2FHP9hL9444vYrDNIF4bWJqgdza9A&u2=Ws94fiX6pb%2F15OBA&width=2560',
        inStock: true,
    },

    // ── GASOLINE POWERED ─────────────────────────────────────────────────
    {
        id: 'oll-gh02',
        model: 'OLL-GH02',
        name: 'Four-stroke Backpack Single Blade Hedge Trimmer',
        category: 'Hedge Trimmer',
        powerType: 'Gasoline',
        badge: 'Gasoline Powered',
        shortDesc: 'Professional 4-stroke 35.8cc backpack hedge trimmer. GX35 engine, 7kg. For large-scale commercial trimming.',
        longDesc: 'The OLL-GH02 is a professional backpack-mounted single-blade hedge trimmer powered by a GX35 four-stroke engine. It distributes the engine weight across the operator\'s back for comfortable, fatigue-free extended operation. Suitable for large farms, golf courses, and commercial landscaping.',
        specs: [
            { label: 'Engine Type', value: '4-stroke GX35' },
            { label: 'Displacement', value: '35.8cc' },
            { label: 'Fuel', value: 'Gasoline / Separate gasoline and oil' },
            { label: 'Max Power', value: '1kW' },
            { label: 'Idle Speed', value: '2800–3200 RPM' },
            { label: 'Net Weight', value: '7 kg' },
            { label: 'Product Size', value: '110×24×26 cm' },
            { label: 'Engine Model', value: 'GX35/DQS' },
        ],
        features: [
            'Backpack weight distribution',
            'GX35 four-stroke engine',
            'Professional commercial grade',
            'Low vibration to operator',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=F7D08NLe%2BnInqlYz5LIV03%2BaZ%2BBC3HC7CWvE%2BWL0PmdLO42BVukmwgbXmDyzh221u0OgCbAkfSxLWknArMfQEwgCh4QIQwWWlBGTCRQ8kq9eh4WUrZtwlw%3D%3D&u2=CTT2rxq4uAwNC85G&width=2560',
        inStock: true,
    },
    {
        id: 'oll-gh03',
        model: 'OLL-GH03',
        name: 'Four-stroke Backpack Single Blade Hedge Trimmer (39.8cc)',
        category: 'Hedge Trimmer',
        powerType: 'Gasoline',
        badge: 'Gasoline Powered',
        shortDesc: 'Upgraded 39.8cc GX35 engine hedge trimmer for maximum power in dense vegetation. 6.5kg.',
        longDesc: 'The OLL-GH03 upgrades to a larger 39.8cc displacement while maintaining the same backpack comfort system. The extra displacement delivers more torque for cutting through very thick or dense woody hedges.',
        specs: [
            { label: 'Engine Type', value: '4-stroke GX35/GX45' },
            { label: 'Displacement', value: '39.8cc' },
            { label: 'Fuel', value: 'Gasoline / Separate gasoline and oil' },
            { label: 'Max Power', value: '1kW' },
            { label: 'Idle Speed', value: '2800–3200 RPM' },
            { label: 'Net Weight', value: '6.5 kg' },
            { label: 'Product Size', value: '110×24×26 cm' },
            { label: 'Engine Model', value: 'GX35/GX45' },
        ],
        features: [
            '39.8cc high-displacement engine',
            'Extra torque for dense thick hedges',
            'Backpack harness distribution',
            'GX35/GX45 reliable engine',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=EsYbANrTCpwc2oE3fBmHO8ObYFFivuAmFbsziCEfnTBXgHWShpd3sy7re6shlX4hJNI%2F4NjSdQmyctc7zMk1y5jUuXRi8SCL9s6aJQQQFmFjyuqW5EVb0WlvwNwpQUIgCRlD6146u9XVyDViK%2FxYw%2BNpRA3tqsghu%2FQB07im573gslFNxa8MGd6%2BAz6x&u2=WEC1IhSiFDg%2FIQXI&width=2560',
        inStock: true,
    },
    {
        id: 'oll-gl01',
        model: 'OLL-GL01',
        name: 'Four-stroke BC-GX35 Side Mount Mower',
        category: 'Lawn Mower',
        powerType: 'Gasoline',
        badge: 'Gasoline Powered',
        shortDesc: 'Backpack GX35 side-mount lawn mower with weeding and soil loosening heads. 6.5kg.',
        longDesc: 'The OLL-GL01 is a versatile backpack mower with GX35 engine and interchangeable heads: weeding head and soil loosening head. The side-mounted design allows access to slopes and narrow areas.',
        specs: [
            { label: 'Engine Type', value: '4-stroke GX35' },
            { label: 'Displacement', value: '35.8cc' },
            { label: 'Fuel', value: 'Gasoline / Separate gasoline and oil' },
            { label: 'Max Power', value: '1kW' },
            { label: 'Idle Speed', value: '2800–3200 RPM' },
            { label: 'Net Weight', value: '6.5 kg / 3kg' },
            { label: 'Product Size', value: '110×24×26 cm' },
            { label: 'Engine Model', value: 'GX35/DQS' },
        ],
        features: [
            'Interchangeable weeding & soil-loosening heads',
            'Side-mount for slopes & narrow rows',
            'GX35 reliable engine',
            'Backpack harness',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=1sQxCdyr3Duhy%2BjlShcY3IohltN0UaSE9uMlupGQm65dIb5k2BBIVaHQBptYIhwAGJFut5beI%2B%2FYjF5fawLlY%2BxpGA52R6488B9nXvauHmjy7WNwpg%3D%3D&u2=gQNxcW7bFvGj5jHw&width=2560',
        inStock: true,
    },
    {
        id: 'oll-gl02',
        model: 'OLL-GL02',
        name: 'Four-stroke BC-GX35 Backpack Mower',
        category: 'Lawn Mower',
        powerType: 'Gasoline',
        badge: 'Gasoline Powered',
        shortDesc: 'GX35 four-stroke backpack mower with weeding & soil-loosening heads. 8kg.',
        longDesc: 'The OLL-GL02 backpack mower uses a GX35 engine and is supplied with both a weeding head and a soil loosening head, making it suitable for grass cutting, weed control, and light soil preparation in one tool.',
        specs: [
            { label: 'Engine Type', value: '4-stroke GX35' },
            { label: 'Displacement', value: '35.8cc' },
            { label: 'Fuel', value: 'Gasoline / Separate gasoline and oil' },
            { label: 'Max Power', value: '0.8 / 1kW' },
            { label: 'Idle Speed', value: '2800–3200 RPM' },
            { label: 'Net Weight', value: '8 kg' },
            { label: 'Product Size', value: '110×24×26 cm' },
            { label: 'Engine Model', value: 'GX35/DQS' },
        ],
        features: [
            'Dual head included (weed + soil)',
            'Full backpack harness system',
            'GX35 engine reliability',
            'Suitable for grass & light soil work',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=dbpFBs3E6zhXuVKZx3dEl0aJU1koHzsEvl2S8SrP4iSkz3d9b2PgxmTx5C8szG7N%2F1lZmj93WUFlgyxacqFaxbjyaNmtV5iqMFc86AsV%2FqmFLe1teULp47zZTNQVR0%2FC2LSDldWb%2FL756673I3Zp5xQ5&u2=5JpT1RqvDA0tgQNr&width=2560',
        inStock: true,
    },
    {
        id: 'oll-gl04',
        model: 'OLL-GL04',
        name: 'Two-stroke Side-Mounted Lawn Mower',
        category: 'Lawn Mower',
        powerType: 'Gasoline',
        badge: 'Gasoline Powered',
        shortDesc: 'Two-stroke BC40-5 side-mounted lawn mower. 42cc, 6kg. Ideal for sloped terrain and orchard floor management.',
        longDesc: 'The OLL-GL04 uses a two-stroke BC40-5 engine offering a lighter overall weight compared to four-stroke options. Side-mounted design is ideal for working between crop rows and on sloped orchard floors.',
        specs: [
            { label: 'Engine Type', value: '2-stroke BC40-5' },
            { label: 'Displacement', value: '42cc' },
            { label: 'Fuel', value: 'Gasoline / Separate gasoline and oil' },
            { label: 'Max Power', value: '1.2kW' },
            { label: 'Idle Speed', value: '2800–3200 RPM' },
            { label: 'Net Weight', value: '6 kg / 8kg' },
            { label: 'Product Size', value: '130×24×26 cm / 110×24×26 cm' },
            { label: 'Engine Model', value: 'F40-5/F40-6' },
        ],
        features: [
            'Two-stroke lightweight engine',
            'Side-mounted orchard configuration',
            'Suitable for sloped terrain',
            'Lower weight for better maneuverability',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=I6AHtSfsTiMgKXkcNz2D0MdkbAxu61iSF%2BjDaPYPixcNm9pfAm3hmaxv%2FkO19rvCU3wo%2F1u%2BqNFOaosrNNE%2BCFeiiKNeEWVGvzgrmA%3D%3D&u2=Q%2FkD%2F3XvXsnN%2BsH5&width=2560',
        inStock: true,
    },
    {
        id: 'oll-gt01',
        model: 'OLL-GT01',
        name: 'Four-stroke GX35 Scarifier (Soil Loosener)',
        category: 'Scarifier',
        powerType: 'Gasoline',
        badge: 'Gasoline Powered',
        shortDesc: 'GX35 engine backpack soil scarifier for deep soil aeration and loosening between crop rows. 11.3kg.',
        longDesc: 'The OLL-GT01 Scarifier is designed for deep soil aeration and loosening between crop rows. It\'s powered by a reliable GX35 four-stroke engine and is a crucial tool for improving soil health, water penetration, and root development across Indian farms.',
        specs: [
            { label: 'Engine Type', value: '4-stroke GX35' },
            { label: 'Displacement', value: '58cc' },
            { label: 'Fuel', value: 'Gasoline / Separate gasoline and oil' },
            { label: 'Max Power', value: '1kW' },
            { label: 'Idle Speed', value: '2800–3200 RPM' },
            { label: 'Net Weight', value: '11.3 kg / 38cc' },
            { label: 'Product Size', value: '110×24×26 cm' },
            { label: 'Engine Model', value: 'GX35' },
        ],
        features: [
            'Deep soil scarification & aeration',
            'Between-row crop cultivation',
            'Improves water penetration',
            'GX35 reliable four-stroke engine',
        ],
        image: 'https://sspark.genspark.ai/cfimages?u1=mdWGRuRu7M9coEOeb4R6j9ABXVktebjsEF%2BYA7dzlWYyIQTH3fnvE3IIcBNZ%2BfxWJGlXz4wiz1BLiwMIzmTRjMosDLAleBPoHHRDCcJDFM2IjluHl%2B8UHRWKsfCcwotTxIZN6OAislEodpqsk5kzM%2F%2FAvN8r5fs0%2B41RVwol8PnzM9TMNOIK%2BpFRrN6SWTuIAO61swmIPFDgsRDOQp2zLte2fyeVOLMD63igTg5VbGGgRBG%2FV%2B%2FigODg8VXJMdf0fp%2FLyaXOsNYgLUFnOx%2FH&u2=5m0OZTQN6PIhyiAl&width=2560',
        inStock: true,
        isNew: true,
    },
];

export const categories = ['All', 'Tea Picking', 'Hedge Trimmer', 'Pole Multi-Tool', 'Lawn Mower', 'Scarifier'] as const;
export const powerTypes = ['All', 'Lithium Battery', 'Gasoline'] as const;
